security:
    encoders:
        App\Entity\User:
            algorithm: bcrypt
    # https://symfony.com/doc/current/security.html#where-do-users-come-from-user-providers
    providers:
        entity_provider:
            entity:
                class: App\Entity\User
                property: identifiant
        in_memory: { memory: ~ }
    firewalls:
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false
        
        main:
            anonymous: ~
            form_login:
                login_path: login
                check_path: login
            logout:
                path: logout
                target: login
            provider: entity_provider
            # activate different ways to authenticate

            # http_basic: true
            # https://symfony.com/doc/current/security.html#a-configuring-how-your-users-will-authenticate

            
            # https://symfony.com/doc/current/security/form_login_setup.html

    # Easy way to control access for large sections of your site
    # Note: Only the *first* access control that matches will be used
    role_hierarchy:
         ROLE_ADMIN: [ROLE_VISITEUR]
         
    access_control:
         
         - { path: ^/login$, roles: IS_AUTHENTICATED_ANONYMOUSLY }
         - { path: ^/$, roles: [ROLE_VISITEUR,ROLE_DEV] }
         - { path: ^/medicament, roles: [ROLE_ADMIN,ROLE_DEV] }
         - { path: ^/liste_rapport, roles: [ROLE_VISITEUR,ROLE_DEV] }
         - { path: ^/praticien, roles: [ROLE_ADMIN,ROLE_DEV] }

    
